name: Auto Pluto Update

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

# 1. ADD THIS BLOCK TO GIVE WRITE PERMISSIONS
permissions:
  contents: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Run scraper
        run: node index.js

      - name: Commit files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto update playlist" || echo "No changes"
          git push --force
